# Configuration for PR Labeller Action
# See: https://github.com/actions/labeler/blob/master/README.md

# Examples
# Add 'label1' to PR if anything changes within 'example' folder or any subfolders
# label1:
#   - example/**/*

# Add 'label2' to PR if any file changes within 'example2' folder
# label2: example2/*

Action:
  - action.yml

Docker:
  - Dockerfile
  - .dockerignore

.NET: 
  - src/EditRelease/**/*

Options: 
  - src/EditRelease/Options.cs

DevOps:
  - .github/**/*
