name: 'Edit Release'
author: 'Irongut <murray.dave@outlook.com>'
description: 'A GitHub Action for editing an existing release.'
branding:
  icon: edit
  color: purple
inputs:
  token:
    description: 'Authentication token, use either GITHUB_TOKEN or a Personal Access Token.'
    required: true
  id:
    description: 'The id of the release to edit, e.g. github.event.release.id.'
    required: true
  name:
    description: 'New text for the name of the release.'
    required: false
    default: ''
  replacename:
    description: 'Set true to replace the release name, false to add to the release name (default).'
    required: false
    default: 'false'
  draft:
    description: 'Set true to change the release to a draft, false to publish the release. Omit if you do not want to change the draft status of the release.'
    required: false
    default: ''
  prerelease:
    description: 'Set true to identify the release as a pre-release, false to identify the release as a full release. Omit if you do not want to change the status of the release.'
    required: false
    default: ''
  body:
    description: 'New text for the body of the release.'
    required: false
    default: ''
  replacebody:
    description: 'Set true to replace the release body, false to add to the release body. (default)'
    required: false
    default: 'false'
  files:
    description: 'A comma separated list of files whose content will be added after the release body text.'
    required: false
    default: ''
  spacing:
    description: 'The number of blank lines required between each addition to the release body. (default = 1)'
    required: false
    default: '1'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/irongut/editrelease:v1.1.0-beta'
  args:
    - '--token'
    - ${{ inputs.token }}
    - '--id'
    - ${{ inputs.id }}
    - '--name'
    - ${{ inputs.name }}
    - '--replacename'
    - ${{ inputs.replacename }}
    - '--draft'
    - ${{ inputs.draft }}
    - '--prerelease'
    - ${{ inputs.prerelease }}
    - '--body'
    - ${{ inputs.body }}
    - '--replacebody'
    - ${{ inputs.replacebody }}
    - '--files'
    - ${{ inputs.files }}
    - '--spacing'
    - ${{ inputs.spacing }}