name: Assign PR to Author

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  contents: read

jobs:
  assign-pr:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - name: Auto Assign PR
      uses: hkusu/review-assign-action@e7863d32a4c6fa2cbad35c5b44e62c34a151b59f
      with:
        assignees: ${{ github.actor }}
