name: Assign to Project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign Issues to Bugs
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/irongut/EditRelease/projects/2'
        column_name: 'Needs triage'

    - name: Assign Issues to Enhancements
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.issue.labels.*.name, 'enhancement')
      with:
        project: 'https://github.com/irongut/EditRelease/projects/1'
        column_name: 'To do'

    - name: Assign PRs to Bugs
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      with:
        project: 'https://github.com/irongut/EditRelease/projects/2'
        column_name: 'In Progress'

    - name: Assign PRs to Enhancements
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.pull_request.labels.*.name, 'enhancement')
      with:
        project: 'https://github.com/irongut/EditRelease/projects/1'
        column_name: 'In progress'
