name: Assign PR to Author

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Assign PR
      uses: samspills/assign-pr-to-author@v1.0.2
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
