name: OpenSSF Scorecards Scan
on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
  schedule:
    - cron: '21 21 * * 6'

permissions: read-all

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # needed to upload the results
      contents: read
      actions: read
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            bestpractices.coreinfrastructure.org:443
            codeload.github.com:443
            github.com:443
            pipelines.actions.githubusercontent.com:443

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          persist-credentials: false

      - name: Scorecards Analysis
        uses: ossf/scorecard-action@865b4092859256271290c77adbd10a43f4779972
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARDS_TOKEN }}
          publish_results: false  # true will not work with Harden Runner!

      - name: Upload Report
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      
      - name: Upload to Code-Scanning
        uses: github/codeql-action/upload-sarif@b398f525a5587552e573b247ac661067fafa920b
        with:
          sarif_file: results.sarif
